### ISSUE TITLE
KeenWrite

### ISSUE THREAD

**Issue by ghost** [bjansen/scoop-apps#1]
Hi,

Would you mind removing KeenWrite from scoop apps?

Thank you!

**Comment by bjansen** [comment]
Hi @DaveJarvis, this project is merely a GUI to search for apps listed in official scoop repositories. I you'd like to remove [your app from scoop](https://github.com/ScoopInstaller/Extras/blob/master/bucket/keenwrite.json) entirely, I suggest you open an issue here instead: https://github.com/ScoopInstaller/Extras/issues

**Comment by ghost** [comment]
Hi again,

https://bjansen.github.io/scoop-apps/extras/keenwrite/

Would you mind removing KeenWrite from that page?

**Comment by ghost** [comment]
See also https://github.com/ScoopInstaller/Extras/issues/10893#issuecomment-1496216817

**Comment by bjansen** [comment]
Data has been sync from the various scoop buckets, and KeenWrite is no longer listed at https://bjansen.github.io/scoop-apps/
