### ISSUE TITLE
Cant get rid of entrys

### ISSUE THREAD

**Issue by SOFTWAREKOCH** [bjansen/scoop-apps#5]
Hi,
pls have a look at the file.
I can not get rid of the "red" entrys.
What ever i do they stay.

Brgds
Dietmar
![SDIO](https://github.com/user-attachments/assets/db0294f0-aec3-4ffc-bfdd-b126848a6af1)

**Comment by bjansen** [comment]
Hi, I have no idea what that software is. It looks like it has a support page here though: https://www.glenn.delahoy.com/community/snappy-driver-installer-origin/
